document.write( '<table width="100%" bgcolor="#ffffff" cellpadding="0" cellspacing="0" border="0">\n' );
document.write( '<tr><td colspan="3" style="height:1px; background-color:navy"></td></tr>\n' );
document.write( '<tr>\n' );
document.write( '<td>\n' );
document.write( '<table width="100%" cellpadding="0" cellspacing="0" border="0">\n' );
document.write( '<tr valign="top">\n' );
document.write( '<td width="140" style="font-size:12px; padding:10px 10px 20px 10px"> <a href="/home.html"><img src="/can1.gif" alt="ChristianAnswers.Net logo" width="115" height="33" /><br />\n' );
document.write( '<img src="/can2.gif" alt="CAN Home" width="57" height="22" /></a><a href="/directry.html"><img src="/can3.gif" alt="Shortcuts" width="58" height="22" /></a><br />Christian Answers Network <a href="/home.html">HOMEPAGE</a> and <a href="/directry.html">DIRECTORY</a><br />\n' );
document.write( '</td>\n' );
document.write( '<td style="font-size:11px; padding:10px 0 20px 0"><a href="/bible/home.html">WebBible home</a>&nbsp;&nbsp; | &nbsp;&nbsp;<a href="/godstory/home.html">God’s Story</a>&nbsp;&nbsp; | &nbsp;&nbsp;<a href="/menu-at1.html">Bible &amp; Theology</a><p>WebBible Encyclopedia… a free service of <a href="/eden/home.html"><b>Eden Communications</b></a> (provider of <a href="/home.html">ChristianAnswers.Net</a>) / <a href="/copyrite.html">Copyright © </a> \n' );
copyright=new Date();
update=copyright.getFullYear();
document.write("2000-"+ update + ", ");
document.write( '<a href="/eden/home.html">Eden Communications</a>. All rights reserved.</p>\n' );
document.write( '<p class="smalltext" style="margin-top:5px">Articles and definitions are written by a variety of experts, including Matthew G. Easton, special contributors, and our staff.</p>\n' );
document.write( '</td></tr></table></td><td align="right" valign="bottom"> <img src="/dictionary/bible-dict.gif" width="93" height="93" border="0" align="right" alt="Bible" /></td></tr></table>\n' );