document.write( '<div class="sectionbox">\n' );
document.write( '<div class="sectionindxtitle">Section Index</div>\n' );
document.write( '<div id="button">\n' );
document.write( '<ul>\n' );
document.write( '<li><a class="nav1" href="/dictionary/biblebooks.html">Books of the Bible (about)</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/men.html">Men</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/women.html">Women</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/places.html">Places</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/animals.html">Animals</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/food.html">Foods</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/drink.html">Drinks</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/king.html">Kings</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/kjvwords.html">King James Words Defined</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/messianicprophecies.html">Messianic Prophecies</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/namesofgod.html">Names of God</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/plants.html">Plants</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/prince.html">Princes</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/prophet.html">Prophets</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/queen.html">Queens</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/river.html">Rivers</a></li>\n' );
document.write( '<li><a class="nav1" href="/dictionary/home.html">Complete Bible word list</a></li>\n' );
document.write( '<li><a class="nav1" href="/home.html">Christian Answers Home</a></li>\n' );
document.write( '</ul>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );