
<h1><span lang='en'>Section 5: Deuteronomy Study Questions </span><span lang='swa'>Sehemu 5: Kumbukumbu la torati maswali ya kujifunza </span></h1>
<h1><span lang='en'>Explain the title of this book. </span><span lang='swa'>Elezea jina la kitabu hiki. </span></h1>
<h2><span lang='en'>The name of this book reveals its purpose: &quot;deuter&quot; meaning&apos;second&quot; and &quot;nomos&quot; meaning &quot;law.&quot; It is a repetition of the laws of Sinai.(17:18) The title of this book is rendered &quot;copy&quot; in 17:18&#44; and means&quot;duplicate.&quot; </span><span lang='swa'>Jina la kitabu hiki hufunua kusudi lake: "kumbukumbu" maaana yake"ya pili" na "torati" maaana yake "sheria." Ni marudioya sheria ya mlima Sinai.(17:18) Jina la kitabu hiki ni Cnakala Diliorodishwa katika 17:18&#44; na kumaanisha"kunakili." </span></h2>
<h1><span lang='en'>Write the key verse to this book and its reference. </span><span lang='swa'>Andika msitari wa ufunguo wa kitabu hiki narejea yake. </span></h1>
<h2><span lang='en'>&quot;I call heaven and earth to record this day against you&#44; that Ihave set before you life and death&#44; blessing and cursing: therefore chooselife&#44; that both thou and thy seed may live:&quot; (30:19) </span><span lang='swa'>Nazishuhudiza mbingu na nchi juu yenu hivileo&#44; kuwa nimekuwekea mbele yako uzima na mauti&#44; baraka na laana; basi chagua uzima&#44; ili uwe hai&#44; wewe na uzao wako; (30:19) </span></h2>
<h1><span lang='en'>Why was this book of &quot;reviews&quot;&#44; &quot;remembrance&quot;&#44; and &quot;repetition&quot; even necessary? </span><span lang='swa'>Kwa nini kitabu kilikuwa ni cha "mapitio"&#44; "ukumbusho"&#44; na "marudio" na hata hivyo ni cha lazima? </span></h1>
<h2><span lang='en'>The old generation that had left Egypt died by the way&#44; except for Joshua and Caleb (1:36; Num. 32:12)&#44; and a new generation must have theold-time laws rehearsed in their hearing.<a href='#2547'>[18]</a></span><span lang='swa'>Kizazi cha kale ambacho kiliondoka Misri kilikufa njiani&#44;isidokuwa Yoshua na kalebu (1:36; Hes. 32:12)&#44; na kizazi kipyalazima kingekuwa na sheria za zamani zilizo karirishwa katika masikio yao.<a href=3D'#endNotes'>[18]</a></span></h2>
<h1><span lang='en'>What is repeatedly given has a motive for Israel&apos;s obedience? </span><span lang='swa'>Ni nini ambacho kilitolewa kwa kurudiarudiachenye kusudi kwa ajili ya utii wa wana wa Israel? </span></h1>
<h2><span lang='en'>The remembrance of deliverance from Egypt is constantly urged as a motive to obedience. (5:15; 10:12&#44;13)sup1 </span><span lang='swa'>Ukumbusho wa ukombozi kutoka Misri ni wosiousiobadilika kusudi la utii. (5:15; 10:12&#44;13)sup1 </span></h2>
<h1><span lang='en'>Why would we say that Deuteronomy is the most integral part of thePentateuch? </span><span lang='swa'>Kwa nini tunasema kumbukumbu la torati sehemu muhimu sana ya Pentatuki? </span></h1>
<h2><span lang='en'>Deuteronomy is a most integral part of the Pentateuch seeing that it condenses and continues the great truths of the first four books of theBible </span><span lang='swa'>Kumbukumbu ni sehemu muhimu sana ya Pentatuki kuonekana kwamba kinatia uzito na kuendeleza kweli kubwa za vitabu viine vya kwanza vya Biblia </span></h2>
<h1><span lang='en'>Moses admonishes in Deuteronomy to &quot;remember especially&quot; something. What was it? Give reference. </span><span lang='swa'>Musa anaonya katika kumbukumbu "kukumbuka hasahasa" kitu fulani. Ilikuwa ni nini? Toa rejea. </span></h1>
<h2><span lang='en'>Remember Especially the day Mount Horeb Burned with Fire andGod Spoke. Deut. 4:10; </span><span lang='swa'>Kumbuka hasahasa siku ya kuteketeza katika mlima Horebu pamoja na moto na mazungumzo ya Mungu. Kumb. 4:10; </span></h2>
<h1><span lang='en'>What two pieces of geography were the Israelites not to contend for or try to possess? </span><span lang='swa'>Ni vipande gani viwili vya jeografia ambavyo vilikuwa wa Israel wasiguse au wasijaribu kuvimiliki? </span></h1>
<h2><span lang='en'>Esau&apos;s Possession and 2:4&#44;5 Lot&apos;sPossession 2:9&#44;19 </span><span lang='swa'>" Umiliki wa Esau 2:4&#44;5 na umiliki wa Lutu 2:9&#44;19 " </span></h2>
<h1><span lang='en'>Using the details given in the book of Deuteronomy&#44; describe Joshua.Give all references to verses used. </span><span lang='swa'>kutumia habari zilizo tolewa katika kitabu cha Kumbukumbu mweelezee Yoshua.Toa rejea zote kwenye mistari iliotumika. </span></h1>
<h2><span lang='en'>And Joshua the son of Nun was full of the spirit of wisdom; forMoses had laid his hands upon him: and the children of Israel hearkened untohim&#44; and did as the LORD commanded Moses.--Deuteronomy 34:9&lt;And ETC.&gt; </span><span lang='swa'>Na Yoshua&#44; mwana wa Nuni&#44; alikuwa amejaa roho ya hekima; maana Musa alikuwa amemwekea mikono yake juu yake; wana wa Israeli wakamsikiliza&#44; wakafanya kama Bwana alivyomwamuru Musa.kumb 34:9&lt;na ETC.&gt; </span></h2>
<h1><span lang='en'>What was Joshua&apos;s ministry essentially? </span><span lang='swa'>Ni nini kilichotiwa katika huduma ya Yoshua? </span></h1>
<h2><span lang='en'>Joshua&apos;s ministry is to cause Israel to possess their inheritance. 1:38; 31:3&#44;7 </span><span lang='swa'>Huduma ya Yoshua ni kusababisha Waisrael kumiliki uridhi wao. 1:38; 31:3&#44;7 </span></h2>
<h1><span lang='en'>Present and explain the laws established concerning marriage inDeuteronomy. Give all references to texts used. </span><span lang='swa'>Wasilisha na kuelezea sheria zilizo dhibitishwa kuhusiana na ndoa katika Kumbukumbu. Toa rejea zote kwenye vifungu vilivyo tumika. </span></h1>
<h2><span lang='en'>PERSONAL STUDY DONE </span><span lang='swa'>SOMO BINAFSI LILILOFANYIKA </span></h2></div><div id='sec-13'>