<h1><span lang='en'>Section 4: Numbers </span><span lang='swa'>Sehemu ya 4: Hesabu </span></h1>
<p><span lang='en'>Purpose and Theme </span><span lang='swa'>Kusudi na Dhamira </span></p>
<p><span lang='en'>This book records Israel&apos;s forty years of wandering in the wilderness and of the equipping of the people fortaking possession of the Promised Land. The central chapters are 13 and 14 inwhich the tribes&#44; in response to Divine command&#44; leave Sinai to possess Canaansome eleven days&quot; march. </span><span lang='swa'>Kitabu hiki kinaweka habari za miaka arobaini ya waisrael kutangatanga jagwani na kujitayarisha kwa watu kuchukuwa umiliki wan chi ya ahadi.Sura za katikati ni 13na 14 katika kile ambacho makabila yaliitikia amri ya Mungu&#44;kuondoka mlima Sinai na kimiliki Kanaani kwa siku kumi na moja za mwezi wa tatu. </span></p>
<p><span lang='en'>The Name-- Numbers </span><span lang='swa'>Jina -Hesabu </span></p>
<p><span lang='en'>TheHebrew title for this book is &quot;b&#601;midbar&quot;&#44; that is&#44; &quot;in the wilderness of.&quot;The name &quot;Numbers&quot; is derived from the fact this book contains the numbering ofthe people of Israel in the wilderness of Sinai (chapters 1-4) and thenumbering of the people afterwards on the plain of Moab (chapter 26). </span><span lang='swa'>Jina la kiebrania kwa ajili ya kitabu hiki ni "b&#601;midbar"&#44; hilo ni&#44;jina la jangwani. DJina DHesabu limetokana na ukweli wa kitabu kuingiza namba za watu wa Waisrael katika jangwala Sinai(Sura ya 1-2) na kuwahesabu watu baadaye kwenye sehemu tambarare yaMoabu(sura ya 26). </span></p>
<p><span lang='en'>Key Verse: </span><span lang='swa'>Msitari wa ufunguo: </span></p>

<h1><span lang='en'>Numbers 9:17-- And when the cloud was taken up from the tabernacle&#44; then after that the childrenof Israel journeyed: and in the place where the cloud abode&#44; there the childrenof Israel pitched their tents. </span><span lang='swa'>Hesabu 9:17&mdash; Na kila lilipoinuliwa lile wingu juu ya ile Hema ndipo wana wa Israeli waliposafiri; na mahali lilipokaa lile wingu&#44; ndipo wana wa Israeli walipopiga kambi yao </span></h1>
<p><span lang='en'>Main People: Moses&#44;Aaron&#44; Joshua&#44; Caleb&#44; Miriam&#44; and the Priests </span><span lang='swa'>Watu wakuu:Musa&#44;Haruni&#44;Yoshua&#44;Kalebu&#44;Miriamu&#44;na Makuhani </span></p>
<p><span lang='en'>Brief Outlines: </span><span lang='swa'>Dondoo fupi:: </span></p>
<p><span lang='en'>The events in the book of Numbers encompass a period of40 years. </span><span lang='swa'>Matukio katika kitabu cha Hesabu kinajumisha kipindi cha miaka 40. </span></p>
<p><span lang='en'>The Preparation for the Journey (1-10) </span><span lang='swa'>Maandalizi kwa ajili ya safariT (1-10) </span></p>
<p><span lang='en'>The Wilderness Wanderings (10-20) </span><span lang='swa'>Mahangaiko jangwanI (10-20) </span></p>
<p><span lang='en'>The Journey to Canaan (21-36) </span><span lang='swa'>Safari ya jangwani (21-36) </span></p>
<p><span lang='en'>The Old Generation (1-14) </span><span lang='swa'>Kizazi cha kale (1-14) </span></p>
<p><span lang='en'>The Transition Era (14-20) </span><span lang='swa'>Usafirishaji kwenda Era (14-20) </span></p>
<p><span lang='en'>The New Generation (21-36) </span><span lang='swa'>Kizazi kipya (21-36) </span></p>
<p><span lang='en'>Numbers opens on the 1st day of the 2nd month of the 2nd year since leaving Egypt with God speaking to Moses in the Tabernacle of the congregation. </span><span lang='swa'>Hesabu inafungua siku ya kwanza ya mwezi wapili wa mwaka wa pili tangu waondoke Misri kwa mazungumzo ya Mungu na Musa katika hema ya kukutania. </span></p>
<p><span lang='en'>1491B.C. to 1451B.C. </span><span lang='swa'>1491K.K hadi 1451K.K </span></p>
<p><span lang='en'>40 Years in theWilderness Wandering&#44; Murmuring &amp; Learning. </span><span lang='swa'>Miaka 40 ya kutangatanga jangwani&#44;manung 9uniko-kujifunza. </span></p>
<p><span lang='en'>INTRODUCTION TO NUMBERS </span><span lang='swa'>UTANGULIZI WA HESABU </span></p>
<p><span lang='en'>Remember&#44; the Bible is first a spiritualBook. No matter what section of the Holy Scripture we study its highest concernwill always be a spiritual one. </span><span lang='swa'>Kumbuka&#44;Biblia ni kitabu cha kiroho.Haijalishi ni sehemu ya maandiko matakatifu tunayojifunza itajihusisha juu zaidi kuwa ndiyo ya kipekee kiroho. </span></p>
<p><span lang='en'>The Bible is useful for business&#44;reliable for history&#44; and a fascinating read&#44; but every precept laid out andrecorded account reveals a spiritual lesson: </span><span lang='swa'>Biblia inafaa kwa ajili ya biashara ya kutegemewa kwa ajili ya Historia&#44;na usomaji wa kuvutia&#44;lakini kila agizo limetolewa na kuweka hesabu inayofunua somo la kiroho: </span></p>
<p><span lang='en'>-1Genesis&quot; creation is an elaborate revelation of salvation. Christ speaks life and light into our chaos and creates new life. </span><span lang='swa'>-1Uumbaji wa Mwanzo ni ufunuo uliochanganuliwa wa wokovu.Kristo anazungumza uzima na nuru kwenye machafuko yetu na kuumba maisha mapya. </span></p>
<p><span lang='en'>-2The Hebrew Exodus parallels spiritual deliverance from the bonds of sin and this world. </span><span lang='swa'>-2Ukombozi sambamba wa kiroho wa kutoka kwaWaebrania kutoka vifungo vya dhambi na dunia hii. </span></p>
<p><span lang='en'>-3InNumbers&#44; the Israelites&quot; journey through the wilderness provokes thought concerning the spiritual themes of full reliance upon God and the life livedwalking in the Spirit. Numbers especially illustrates sanctification which aseparation from E </span><span lang='swa'>-3Katika Hesabu safari ya waisrael kiupitiajangwani inachochea wazo kuhusu dhamira za kiroho ya utambuzi wote kuhusu Mungu na maisha ya kuishi na kutembea katika Roho. Hesabu kwa halisi inaelezea utakaso ambao ni kutengwa kutoka Misri </span></p>
<p><span lang='en'>To the spiritual mind&#44; a study of the O.T. law is quickening and provocative&#44; but the carnal mind might find it lackluster. </span><span lang='swa'>Kwenye ufahamu wa kiroho&#44;somo la Agano la kale.sheria ni nyepesi kuchochea&#44;lakini ufahamu wa kimwili waweza kuipata ikiwa na upungufu wa uhai. </span></p>
<p><span lang='en'>ICorinthians2:14-16--But the natural man receiveth not the things of theSpirit of God: for they are foolishness unto him: neither can he know them&#44;because they are spiritually discerned. 15 But he that is spiritual judgeth allthings&#44; yet he himself is judged of no man. 16 For who hath known the mind ofthe Lord&#44; that he may instruct him? But we have the mind of Christ. </span><span lang='swa'>I Wakor2:14-16&mdash;Basi mwanadamu wa tabia ya asili hayapokei mambo ya Roho wa Mungu; maana kwake huyo ni upuzi&#44; wala hawezi kuyafahamu&#44; kwa kuwa yatambulikana kwa jinsi ya rohoni. 15 Lakini mtu wa rohoni huyatambua yote&#44; wala yeye hatambuliwi na mtu. 16 Maana&#44; Ni nani aliyeifahamu nia ya Bwana&#44; amwelimishe? Lakini sisi tunayo nia ya Kristo </span></p>
<p><span lang='en'>The study of the offerings and priesthood is insightfully rich in teaching us how to approach a holy God andour service to Him. The blood of goats point to the Savior Jesus Christ and theinstruction of Moses is council from the ALMIGHTY GOD. </span><span lang='swa'>Somo la sadaka na ukuhani ni utajiri wa utambuzi kutufundisha jinsi ya kumsogelea Mungu mtakatifu na huduma yetu kwake.Damu ya mbuzi inamlenga mwokozi Yesu Kristo na maelekezo ya Musa ni ushauri kutoka MUNGU MKUU. </span></p>
<p><span lang='en'>Do not study the Bible merely intellectually as a scholar&#44; but devour the spirit of Its message heartily! </span><span lang='swa'>Usijifunze Biblia tu kwa akili kama msomi&#44;bali meza roho ya ujumbe wake kwa moyo! </span></p>
<p><span lang='en'>2 Corintians3:6-8--Who also hath made us able ministers of the new testament; not of the letter&#44; but of the spirit: for the letter killeth&#44; but the spirit giveth life.7 But if the ministration of death&#44; written and engraven in stones&#44; wasglorious&#44; so that the children of Israel could not stedfastly behold the faceof Moses for the glory of his countenance; which glory was to be done away: 8How shall not the ministration of the spirit be rather glorious? </span><span lang='swa'>2 Wakr3:6-8&mdash;Naye ndiye aliyetutosheleza kuwa wahudumu wa agano jipya; si wa andiko&#44; bali wa roho; kwa maana andiko huua&#44; bali roho huhuisha. 7 Basi&#44; ikiwa huduma ya mauti&#44; iliyoandikwa na kuchorwa katika mawe&#44; ilikuja katika utukufu&#44; hata Waisraeli hawakuweza kuukazia macho uso wa Musa&#44; kwa sababu ya utukufu wa uso wake; nao ni utukufu uliokuwa ukibatilika; 8 je! Huduma ya roho haitazidi kuwa katika utukufu? </span></p>
<p><span lang='en'>The thirty-six chapters of Numbers journal the details of a spiritual pilgrimage. It is a spiritual journal of spiritual journey toward a spiritual inheritance. </span><span lang='swa'>Sura thelathini na sita za hesabu ya safarini habari za mahujaji wa kiroho kuelekea urithi wa kiroho. </span></p>