<h1><span lang='en'>Joseph (30:1-50:26)</span><span lang='swa'>Yusufu (30:1-50:26)</span></h1>

<h2><span lang='en'>His Birth</span><span lang='swa'>His Birth</span></h2>

<p><span lang='en'>Rachel was barren and very frustrated because of it. She even turned her frustration on her husband&#44; Jacob and blamed him for her barrenness. Out of their marital spat sprouted a plan in Rachel&apos;s mind--they would borrow from Abraham and Sarah&apos;s idea of substitutionary impregnation. This and further competitive efforts with Leah resulted in ten children for Jacob&#44; but failed to satisfy the heart of Rachel because the desire of her heart was to have a child of her own. Verse 22 says that God &quot;remembered&quot; Rachel and gave her a son. This does not infer that God forgot Rachel&#44; but emphasizes the point God recognized or was mindful of her at this ordained time. Rachel felt forgotten and worthless&#44; but God had a plan to bless her. </span><span lang='swa'>Raheli alikuwa tasa na alikatishwa tama kwasababu hiyo.Na hata aligeuza ile kukatishwa tamaa kwake juu ya mme wake&#44;Yakobo na kumlaumu kwa ajili utasa wake.Inje ya ugomvi wa ndoa yao ulichipuka mpango moyo D wa Raheli 4wangefuatisha toka wazo la Ibrahimu naSara la utiaji mimba mbadala. Hili na juhudi za mashindano zaidi na Lea ilotokea katika watoto kumi wa Yakobo lakini ilishindikana kusafisha moyo wa Raheli kwa sababu tamaa ya moyo wake ilikuwa kupata mtoto wake mwenyewe.Msitari wa 22 unasema kwamba Mungu Calimkumbuka D Raheli na kumpatia mwana.Hii haerejei kwamaba Mungu alimsahau&#44;bali inasisitiza kuonyesha Mungu alitambua au alikuwa akimwazia kwenye wakati mwafaka.Raheli alijisikia amesahaulika na kutositahili&#44;lakini Mungu. alikuwa na mpango wa kumbariki. </span></p>
<p><span lang='en'>Rachel&apos;s self-worth was wrapped up in her ability to give Jacob at least one son and she felt like a reproach because of her barrenness. Her testimony of victory was that God had taken away her reproach in giving her a son&#44; Joseph. Only God can take away the reproach of sin. There is no ability in man to please God outside of the redemptive work ofChrist. No effort of the sinner can produce life&#44; but by the miracle of salvation is our &quot;barrenness&quot; and &quot;reproach&quot; removed! Not only did God heal her barrenness and remove her reproach&#44; but he restored her faith. She called her son Joseph meaning may God add or increase; added because she knew theLord would add to her another son. She was right because she eventually gave birth to Benjamin. Alas&#44; Rachel died from the difficulty of his birth.</span><span lang='swa'> Kusitahili-kibinafsi kwa Raheli ilikuwa imefungiwa juu katika uwezo wake kumpa Yakobo angalau mwana moja na alijihisi kama kujilaumu kwa sababu utasa wake.Ushuhuda wake wa ushindi ulikuwa kwamba Mungu amechukuwa aibu yake kwa kumpatia mwana&#44;Yusufu. Mungu pekee anaweza kuondoa aibu ya dhambi.Hakuna uwezo katika binadamu wa kumpendeza Munguinje ya kazi ya wokovu wa Kristo. Hakuna juhudi ya mwenye dhambi kuweza kuzalisha uzima&#44;bali muujiza wa wokovu ni Cutasa wetu Dna Caibu Dkuondolewa!sio tu kwamba Mungu anaponya utasa wake na kuondoa aibu yake&#44;bali alirudisha imani yake.Alimwita mwanaye Yusufu kumaanisha Mungu aweza kuongeza au ongezeko;aliongezewa kwa sababu alijua Bwana angeweza kumwongezea mtoto mwingine.Alikuwa sahihi kwa sababu mwishowe alimzaa Benjameni. Alas&#44; Raheli alikufa kutokana na matatizo ya uzazi.</span></p>

<h2><span lang='en'>His Character</span><span lang='swa'>His Character</span></h2>

<h3><span lang='en'>Excellence</span><span lang='swa'>Excellence</span></h3>

<p><span lang='en'>Joseph was one of the most outstanding men of the Bible because of his personal character and despite intense difficulties overall excellence in life. Jacob&apos;s favoritism in giving him the coat of many colors and even the Lord&apos;s special attention to Joseph in giving him dreams of future exaltation provoked his brothers to envy. </span><span lang='swa'>Yusufu alikuwa moja ya watu wanoonekana kwamsimamo wa Biblia kwa sababu ya tabia ya utu wake na magumu ya hisia yasiyoya matakwa kushinda ubora wote katika maisha. Upendeleo wa Yakobo katika kumpa koti lenye rangi nyingi na hata usikivu maalumu wa Bwana ulikuwa kwa Yusufu katika kumpatia ndoto za utukufu wa mwisho uliowakasirisha ndugu zake kwa wivu. </span></p>

<p><span lang='en'>COAT: It was a coat of long sleeves which was the garment of a boss and not a worker. It was a coat of many colorswhich greatly differed from everyday work clothes which necessitated noexpensive dyes or colorings. The coat undeniably made a distinction betweenJoseph and his brethren. (His father&apos;s special favor toward Joseph was becauseof Rachel.) </span><span lang='swa'>KOTI: Lilikuwa koti la kanzu ndefu ambalo lilikuwa vazi la mkuu wa kazi na sio la mfanya kazi.Lilikuwa kanzu la rangi nyingi ambalo kwa ukubwa lilitofautiana na mavazi ya kazi za kila siku ambayoyalilazimishwa hakuna marembo ya gharama au mtindo wa utiaji rangi wa kisanii.Kanzu kwa wazi ilifanywa kwa utofauti kati ya Yusufu na ndugu zake.(upendeleo maalumu wa baba yake kwa upande wa Yusufu ulikwa kwa sababu ya Raheli.) </span></p>

<h3><span lang='en'>Dreamer</span><span lang='swa'>Dreams</span></h3>

<p><span lang='en'>Joseph was a spiritual though youthful dreamer whose dreams came true even though he was initially rejected by his brethren. Hold onto the dreams God gives because they are a compass for life.</span><span lang='swa'>Yusufu alikuwa kijana mdogo mwuota ndoto ambaye ndoto zake zilikuwa kweli hata kama mwanzoni alikataliwana ndugu zake. Anashikilia ndoto ambazo Mungu anatoa kwa sababu wao ni kikomo kwa ajili ya maisha.</span></p>

<p><span lang='en'>DREAM 1: His brothers&quot; sheaves of wheat bowed down to Joseph&apos;s sheaf. </span><span lang='swa'>NDOTO 1: miganda ya ndugu zake ya ngano ilisujudia mganda wa Yusufu. </span></p>
<p><span lang='en'>DREAM 2: Sun&#44; Moon and Eleven Stars bowed down to Joseph. </span><span lang='swa'>NDOTO 2: Jua&#44;Mwezi na nyota kumi na moja zilimsujudia Yusufu. </span></p>

<h3><span lang='en'>Faithful</span><span lang='swa'>Faithful</span></h3>

<p><span lang='en'>Joseph was enslaved&#44; falsely accused and forgotten by men&#44;but was faithful even in the hard places. Joseph enjoyed the presence of God and won the confidence of his master. Joseph had physical good looks&#44; but it was never a snare to him. Joseph resisted temptation and was silent amid foul accusations and unjust punishment. Joseph the interpreter of dreams proved that&quot;prison walls do not a prisoner make.&quot; Joseph is a perfect type of Christ and of the Overcomer. Joseph manifested great wisdom&#44; brotherly love&#44; filial devotion and utter submission to God. (Gen. 43:20; 45:8&#44;14&#44;23; 47:7.) He knew how to return good for evil and God preserved his family through his generosity. </span><span lang='swa'>Yusufu alitiwa utumwani&#44;alishitakiwa kwa uwongo na alisahauliwa na watu&#44;lakini alikuwa mwaminifu hata katika mazingira magumu.Yusufu alifurahia uwepo wa Mungu na kushinda ujasiri wa bwana wake.Yusufu alikuwa na uzuri wa kimwili&#44;lakini hiyo kamwe haikuwa mtego kwake.Yusufualipinga jaribu na alikuwa kimya katikati ya mashitaka ya kuchukiza na adhabu isio ya haki.Yusufu mfasiri wa ndoto alithibiti kuta za gereza ili kumwokoa mnyweshaji mfungwa. DYusufu ni mfano kamili wa Kristo na wa mshindi.Yusufu alidhihirisha hekima kubwa&#44;upendo wa kindugu&#44;moyo wa kupenda ibada na unyenyekevu kamili kwa Mungu. (Mwanzo. 43:20; 45:8&#44;14&#44;23; 47:7.) Alijua kugeuka vema kwa ajili uovu na Mungu alihifadhi familia yake kwa njia ya ukarimu wake. </span></p>