<h1>The Bible: The Story of Redemption</h1>

<p> Many critics of the Bible may say that it is just a collection of stories written by many men that were later gathered into one collection and titled <i>the Holy Bible</i>. They believe it is just a bunch of fancified accounts of Israel’s history and inane cognitions about such things as women eating forbidden apples and men being swallowed by giant sea creatures. They do not believe that the Bible was written by one author, but rather they believe that it was created by various, unrelated men that chose to believe in a Supreme Being throughout the stages of time. A comprehensive study of the Bible that compares all of the 66 books will disprove these false suppositions and will reveal that the Bible is not just <i>a collection of stories</i>, but that it is in reality <i>one story</i>, namely, <i>The Story of Redemption</i>.</p> 
 
<p><b>The Theme of the story</b></p> 
<p>    Though different books treat the subject in different manners, there is one clear theme that runs through the entire Bible, and that is the redemption of mankind. In the beginning, God had a desire to create a being that could have fellowship with Him, and that being was mankind. Because of Adam’s sin in the garden, man lost that place of fellowship with God, but God had a plan to redeem (to recover or buy back) man to that place of fellowship. This plan of redemption is the main theme of the Bible as a whole, and thus the Bible can be called <i>The Story of Redemption</i>.</p> 
<p><b>The characters of the story</b></p> 

<p>The <b>protagonist</b> in a story is the one that moves the action of the story and is usually the hero or heroine, which in the Bible the protagonist is none other than the Son of God, commonly referred to as Jesus Christ. He is the Redeemer, the One who had the ambition and the ability to save mankind from their helpless estate. Many think of Christ as only a principle character of the New Testament, but they fail to realize that He is actually the main character of the entire Bible, for He is an essential part of every one of the 66 books of the Bible and not only the four Gospels. The Old Testament is riddled with typological objects and characters, prophetical foretellings, and actual appearances of Christ and His redeeming power for mankind. He is the One that was promised to Eve that would redeem her fallen offspring by bruising the serpents head (Genesis 3:15), He is the One that appeared to Moses in the burning bush to announce the emancipation of Israel from Egyptian bondage (Exodus 3:2-8), He is the Redeemer of Whom Job proclaimed a revelation of His vitality (Job 19:25), and He is the Fourth Man in the furnace that rescued the pious Hebrew Children from a fiery fate (Daniel 3:24, 25). Throughout the entirety of the Bible we see this one Christ with His one plan for redemption for lost mankind; this universal protagonist is evidence that the Bible is one complete volume and not just a collection of hap-hazard stories about random themes. </p> 
<p>In a story the <b>antagonist</b> is the one that stands in opposition to the protagonist, and in the Bible this is quite obviously the devil. We see at the very beginning of the Bible how he induces the destruction of God’s fellowship with mankind by enticing Eve to eat the fruit from the tree of the knowledge of good and evil, and we see him working throughout the other accounts trying to hinder Christ’s plan of redemption (we do not read of many references of him by name throughout the Old Testament, but we see from the book of Job that he is behind acts of persecution against God and His saints), and we even see him go face to face in a verbal battle with Christ as is accounted in the fourth chapters of both Matthew and Luke.</p> 

<p>The <b>supporting characters</b> of a story are those that play a part in the plot, but they are not major characters. In the Bible there are many supporting characters, and there are two certain categories of them that remain the same throughout the entire Bible even though their names and specific circumstances may change—these are the saints and the sinful. The saints are those that sought and received the redemption of Christ; in the Old Testament they are those of the children of Israel and in the New Testament they consist of followers of Jesus, or Christians. The sinful are the unredeemed enemies of God that have no desire for salvation and who persecute God's people.</p> 
<p>    The consistency of these character categories throughout the entire Bible shows us it's unified theme and story plot. You will not find accounts in the Bible that center around other types of people, nor will emphasis be added to any individual besides that which categorizes them as either saints or sinful (i.e. you do not find many descriptions about a person’s physical appearance, nor about their personality traits, but you will hear over and over again how this individual pleased God or how this person did that which was evil in the sight of the Lord). The Bible is not concerned with documenting characters of history, but it’s purpose is to show how man responded to the plan of redemption, and you will find this fact true of every chapter of every book of the Bible.</p> 
<p><b>The outline of the story</b></p> 
<p>    In a story there are five basic parts that make up the outline, and they are as follows: exposition, rising action, climax, falling action, and resolution.</p> 
<p>1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span>Exposition. The <b>exposition</b> is the beginning of the story where the characters and setting are revealed. For the Bible, this is the book of Genesis, in which the main characters (God, Christ, the devil, the saints, and the sinful) and the setting (earth that has been conquered by sin) are introduced to the reader. </p> 
<p>2.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span>Rising action. The <b>rising action</b> is where the events in the story become complicated and the conflict in the story is revealed; it is all the events between the exposition and the climax. In the Bible this is all the books of the Old Testament excluding Genesis (Exodus to Malachi). Through these books we see the conflict of the story appear over and over again; the conflict is that mankind desires to once again have fellowship with God, and yet the devil and their sin hinders them from attaining to such a place. The realization resurfaces constantly that they cannot restore themselves to this position, but that they needed a Messiah to come and redeem them from their hopeless estate.</p> 
<p>3.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span>Climax. The highest point of interest and turning point of the story is known as the <b>climax</b>. This is the point of the movie that you fast-forward to and watch over and over again because it is action packed and thrilling to behold even though it already has been seen dozens of times. This is what the four Gospels are to the Bible. Here we see Christ coming into the world as the long awaited Messiah to redeem mankind. We see Him suffer and die on the cross, not because of His sins, but for the sins of the whole world, and we see Him rise from the grave three days after He had been dead, finalizing the plan of redemption. It is truly the most beloved portion of Scriptures being read over and over again several times a year by many Christians.</p> 
<p>4.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span>Falling action. This is where the events and complications of the story begin to resolve themselves, and in the Bible this is namely the book of Acts and the Epistles (Romans to Jude). While we saw redemption provided for at the climax of the story in the four Gospels, we did not then see many men enter into that provision of redemption, and it is here in these books succeeding the Crucifixion and Resurrection of Christ that we see man become truly redeemed from the penalty and power of sin. As the number of these redeemed men and women (referred to as the church) begins to grow, it is without doubt to the reader that the plan of redemption has been fully accomplished and that the same plan can have an effect on their lives.</p> 
<p>5.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span>Resolution. The <b>resolution</b> of a story is the very end where all the loose ends are tied up and it is cemented in the reader’s mind what the final outcome is. For the Bible this is the book of Revelation, for here we see the antagonist, the devil, cast into the lake of fire and we see the protagonist, Jesus Christ, united with the supporting characters, the saints, in an eternal union of fellowship. </p> 
<img src="/dbi/images/story-arc.jpg" alt="The Story of Redemption"></p> 
<p>From the above arguments, you can see that the Bible as a whole has all the elements that make up a good story in a literary sense, and though it may have more supporting characters than Dodie Smith’s <i>101 Dalmatians</i> and it may be almost 30% longer than Count Leo Tolstoy’s <i>War and Peace </i>(The Bible has <span class=apple-style-span><span style='color:black'>788,280 words, while War and Peace has </span></span><span class=apple-style-span><span style='color:black'>560,000 words)</span></span>, I believe the Bible is the greatest book ever written. I am not alone in this thought, for men of prestige have made mention of the greatness of the Bible. American patriot Patrick Henry said, <span class=apple-style-span><span style='color:black'>&quot;The Bible is worth all other books that have ever been printed.&quot; One of the most famous novelists of all time, Charles Dickens, said that &quot;The New Testament is the best book </span></span>the world has ever known or will know.&quot; And it is said that literary legend Sir Walter Scott on his deathbed said to a nearby friend, “Bring me the Book,” to which the friend inquired, “Which book?” Sir Walter replied, “There is but one Book,” referring to the Bible.</p> 
<p>    Although the Bible has all the elements that make up a good story, it is so much more than just a good story; it is God’s book of instructions to man. Every page is worth reading and every thought is worth absorbing, for in doing so, you will find that it is the only for you to “live happily ever after.”</p>