<questions>
<title><english>Study Questions 1 - Introduction</english><swahili>Maswali Ya Kujifunza 1 - Utangulizi</swahili></title>

<question><text><english>What is the meaning of Doctrine?</english><swahili>Nini maana ya Mafundisho ya Biblia?</swahili></text><hint></hint><answer><english>Doctrine is the fundamental truths of the Bible arranged in a systematic form. </english><swahili></swahili></question>
<question><text><english>Why do we describe theology or doctrine as &ldquo;a science&rdquo;? </english><swahili>Kwa nini tunaielezea theolojia au Mafundisho ya Biblia kama sayansi?</swahili></text><hint></hint><answer><english>Because it consists of facts relating to God and Divine things systematically and logically arranged. </english><swahili></swahili></question>
<question><text><english>What is the connection between theology and religion? </english><swahili>Kuna uhusiano gani kati ya theolojia na dini?</swahili></text><hint></hint><answer><english>Theology is knowledge of God&#44; and religion is the practice of what we know. </english><swahili></swahili></question>
<question><text><english>What is the difference between a doctrine and a dogma?</english><swahili>Kuna tofauti gani kati ya Mafundisho ya Biblia na mapokeo ya wanadamu (dogma)?</swahili></text><hint></hint><answer><english>Dogma is man&rsquo;s statement of the truth set forth in a creed; while&#44; doctrine is the fundamental truths of the Bible arranged in a systematic form. </english><swahili></swahili></question>
<question><text><english>What connection does doctrine have with the truth found in the Word of God? </english><swahili>Kuna uhusiano gani kati ya Mafundisho ya Biblia na ukweli unaopatikana katika neno la Mungu?</swahili></text><hint></hint><answer><english>That is exactly what doctrine is: the truths found in the word of God arranged in a systematic form. </english><swahili></swahili></question>
<question><text><english>What connection does doctrine have with Salvation?</english><swahili>Kwa uhusiano gani kati Mafundisho ya Biblia na wokovu?  Toa Maandiko kuthibitisha.</swahili></text><hint></hint><answer><english>Give a Scripture reference. Correct doctrinal knowledge is essential to salvation. I Timothy 4:16 </english><swahili></swahili></question>
<question><text><english>What connection does doctrine have with development of Christian character?</english><swahili>Kwa uhusiano gani kati ya Mafundisho ya Biblia na maeudeleo ya tabia ya Mkristo?</swahili></text><hint></hint><answer><english>Doctrinal knowledge is essential to the full development of Christian character. </english><swahili></swahili></question>
<question><text><english>Give verbatim I Tim. 4:16. Take heed unto thyself&#44; and unto the doctrine; continue in them: for in doing this thou shalt both save thyself&#44; and them that hear thee. </english><swahili>Andika neno kwa neno  I Timotheo 4:16.</swahili></text><hint></hint><answer><english>1 Timothy 4:16&mdash;Take heed unto thyself&#44; and unto the doctrine; continue in them: for in doing this thou shalt both save thyself&#44; and them that hear thee.</english><swahili></swahili></question>
<question><text><english>Give verbatim II Tim. 2:15.</english><swahili>Andika neno kwa neno  II Timotheo 2:15.</swahili></text><hint></hint><answer><english>Study to shew thyself approved unto God&#44; a workman that needeth not to be ashamed&#44; rightly dividing the word of truth. </english><swahili></swahili></question>
<question><text><english>Give verbatim II Tim. 3:16. </english><swahili>Andika neno kwa neno  II Timotheo 3:16.</swahili></text><hint></hint><answer><english>All scripture is given by inspiration of God&#44; and is profitable for doctrine&#44; for reproof&#44; for correction&#44; for instruction in righteousness : </english><swahili></swahili>
</questions>