INSERT INTO `dbi`.`courses_questions` (`cq_id`, `cq_cdl_id`, `cq_question`, `cq_answer`, `cq_weight`, `cq_hint`) VALUES 
(NULL,32,'Who was this a revelation of?','It is a revelation of Jesus Christ.',5,NULL),
(NULL,32,'Who gave Him this revelation?','God gave this revelation.',5,NULL),
(NULL,32,'What is the substance of this revelation?','The essential substance of this book is that it is prophecy.',5,NULL),
(NULL,32,'Why is it a key to this revelation?','Because this revelation has to do with the FUTURE and not the past.',5,NULL),
(NULL,32,'In what kind of language is much of this revelation written?','Much of this revelation is in symbolic language.',5,NULL),
(NULL,32,'Who is the scribe of this revelation?','John the Beloved the apostle is the scribe of this revelation.',5,NULL),
(NULL,32,'What is the value of this revelation?','It is REWARDING and ENLIGHTENING.',5,NULL),
(NULL,33,'What are the sources of this salutation?','The Father&#44; the Son and The Holy Ghost',5,NULL),
(NULL,33,'What are the subjects of this salutation?','33. The Churches 2. Their Location 3. Their Need',5,NULL),
(NULL,33,'What was the substance of this salutation?','33. Grace 2. Peace 3. Consolation 4. Confirmation',5,NULL),
(NULL,33,'What were the circumstances of this salutation?','Common: 1. Brotherhood 2. Suffering 3. Royalty 4. Promise 5. Place',5,NULL),
(NULL,34,'How did John receive the vision?','John received the vision by the Holy Spirit.',5,NULL),
(NULL,34,'What was he commanded to do with the vision?','He was commanded to write it in a book and share it.',5,NULL),
(NULL,34,'How was the vision announced?','By a great voice as of a trumpet.',5,NULL),
(NULL,34,'What was the first scene of the vision?','The Church -- Seven Golden Candlesticks',5,NULL),
(NULL,34,'What was the second scene of the vision?','The Glorified Christ -- One Like unto the Son of Man',5,NULL),
(NULL,34,'What was the third scene of the vision?','The Lord&apos;s Ministers -- Seven Stars',5,NULL),
(NULL,34,'Where does the Lord hold His ministers?','He holds them in His right hand.',5,NULL);