/*
IDENTIY WHICH DOCUMENTS EACH QUESTION
REFERENCES AND REPLACE ## with ID
*/

INSERT INTO `dbi`.`courses_questions` (`cq_id`, `cq_cdl_id`, `cq_question`, `cq_answer`, `cq_weight`, `cq_hint`, `cq_order`, `on_sq`, `on_qz`, `on_fl`) VALUES 

/*Study Questions: 2 &ndash; Anthropology */
(NULL, ##, 'What does special creation mean?', '<u>Special Creation </u>means that all living organisms will produce after it&rsquo;s kind.', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does being made in the image and likeness of God refer to?','It has reference particularly to a moral and intellectual likeness. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Can one form of life develop from another form of life; that is&#44; can a snail become a fish&#44; etc.?','No. One form of life cannot develop from another form of life. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is a species?','A class of plants or animals which have characteristic properties in common and can be indefinitely propagated without changing those characteristics. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the test by which the distinction of species is known?','If living organisms can be paired together and so propagate indefinitely a fertile offspring&#44; they are of the same species. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is evolution a scientifically proven fact?','No. Evolution is a theory. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What was the original condition of man?','Endued with lofty intellectual faculties. Created a perfect being. Created a free moral agent. Created with an inherent religious instinct. Created sinless.', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Does man really have a choice between right and wrong?','Yes. Man was created a free moral agent having the freedom of choice. ', 5, NULL, 1, 1, 0, 1),
(NULL, ##, 'By way of creation did man have any consciousness of moral responsibility?','Yes. Man was created with an inherent religious instinct&#44; which made him conscious of moral responsibility to God&#44; ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'In what kind of state was man when he was created?','Man was created sinless and innocent of evil. ', 5, NULL, 1, 1, 0, 0),


/* SQ: 3 */
(NULL, ##, 'What is Harmartiology?','Harmartiology is the doctrine or science of sin. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Why is it referred to as a science?','It is called a science because it consists of systematically and logically arranged facts. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is the most tragic fact connected with man?','The most tragic even connected with man is his fall into sin. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does Genesis 3:1-6 reveal?','It reveals that the first man fell. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What were the steps in the fall?','Listening to slanders about God. Doubting God&rsquo;s Word and His love. Looking at what God has forbidden. Lusting for what God has prohibited.', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Name the two trees of destiny in Genesis 2?','a) the tree of life.  b) the tree of knowledge of good and evil.', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Why was the forbidden tree placed in the garden?','It was placed in the garden as a test for man. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What agent did Satan employ in the temptation?','Satan employed the agent of a serpent in the temptation. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What was the outstanding characteristic of the agent?','The serpent was more subitl than any other beast. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What were the evidences of a guilty conscience?','They ran&#44; hid&#44; and tried to cover themselves. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Give the verse in Genesis 3 that promised redemption.','Genesis 3:15&mdash;<i>And I will put enmity between thee and the woman&#44; and between thy seed and her seed; it shall bruise thy head&#44; and thou shalt bruise his heel.</i>', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Give one scripture to prove all have sinned.','Romans 3:23&mdash;<i>For all have sinned&#44; and come short of the glory of God;</i>', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What effect does Adam&rsquo;s sin have in us? Give reference.','The effect of Adam&rsquo;s sin upon all humanity is death. Romans 5:12; 6:23 ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'To what is the whole race in captivity?','The whole race of man is hopelessly captive to sin and satan. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'To what extent is man affected by sin?','The <i>entire</i>nature of man&mdash;mentally&#44; spiritually&#44; morally&#44; and physically&mdash;is sadly affected by sin. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does sin do to the understanding? Give reference.','Sin darkens the understanding. Eph. 4:18 </u>[and/or] <u>1 Cor. 2:14', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does Jeremiah say is wrong with the heart?','The heart is deceitful and wicked. Jer. 17:9&#44;10 ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What happens to the mind and conscience?','The mind and conscience are defiled. Gen. 6:5; Titus 1:15 ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'How does sin influence the Flesh and Spirit?','The flesh and spirit are defiled. 2 Cor. 7:1 ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What happens to the will when falling into sin?','The will is enfeebled. Rom. 7:18 ', 5, NULL, 1, 1, 0, 0),

/* SQ: 4 */
(NULL, ##, 'What does Soteriology mean?','Soteriology is the doctrine or science of salvation. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Name the five cardinal doctrines.','Salvation&#44; Healing&#44; Baptism&#44; Sanctification&#44; Second Coming ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does the word salvation include?','Salvation is an all inclusive word: deliverance&#44; safety&#44; preservation&#44; soundness&#44; restoration&#44; healing ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What are the three aspects of salvation?','Justification&#44; Regeneration&#44; and Sanctification ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Is salvation an outward or inward experience?','Salvation is both and outward and inward experience. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does justification mean?','Justification means to be set in right relationship with God. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does regeneration mean?','Regeneration is being born into the family of God. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does sanctification mean?','Sanctification is being separated from sin and unto God. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is meant by the &lsquo;conditions of salvation&rsquo;?','God&rsquo;s requirements in the man whom He accepts for Christ&rsquo;s sake and on whom He freely bestows the blessings of the gospel of grace. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What are the conditions of salvation? Give references.','Repentance &mdash; Faith &mdash; Confession. Mark 1:15; Acts 22:16; 16:31; Romans 10:9&#44;10; Hebrews 11:6; Acts 8: 13&#44;21 ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the difference between repentance and faith?','Faith receives salvation&#44; but repentance renounces sin. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is the command of God to all men everywhere?','God&rsquo;s command to all men everywhere is to repent. Acts 17:30 ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'How does the Holy Spirit help a person to repent?','The Holy Spirit brings conviction of sin. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is intellectual faith sufficient for salvation? Give reference.','No. We must have more than what the devils have! James 2:19 ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Give verbatim Hebrews 11:6.','But without faith it is impossible to please him: for he that cometh to God must believe that he is&#44; and that he is a rewarder of them that diligently seek him. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the difference between belief and faith?','Faith is a Divine activity and Believing is a human action. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is it that produces faith? ','The Revealed Word produces faith. </u>(Faith cometh by hearing and hearing by the Word of God.', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does conversion mean? ','Conversion means a change of mind&#44; direction and character. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'How is conversion to be distinguished from salvation? ','Conversion describes the human or manward side of salvation. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Is conversion entirely a matter of human effort? ','Conversion is not entirely a matter of human effort; it requires the aid and ability of God. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Which comes first&#44; regeneration or conversion? ','Regeneration and conversion are simulations. [Regeneration – cause / Conversion – effect &lt;Working together&gt; ]', 5, NULL, 1, 1, 0, 0),


/* SQ: 5 */
(NULL, ##, 'What kind of a term is justification?','Justification is a judicial term.', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the nature of justification? <u>Divine Acquittal. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'How is this made available to individuals? <u>By faith. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is this merely a temporary state or a permanent state? Give Scripture. ',
(NULL, ##, 'Justification is a state of acceptance in which the believer stands. (Rom. 5:2) ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is Justification a matter of past behavior or present imperfection? ','Justification is not a matter of either past behavior or present imperfection. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'In what sense is justification subtraction and addition? ','Subtraction-takes away our sin. Addition-God imputes to us righteousness. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Why is justification necessary? Give scripture. ','Man is condemned. All have sinned Job 9:2; Acts 16:30; Rom. 3:23 ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What were the steps in the downfall of the Gentiles? ','Once Knew God. Glorified Him not as God. Neither were thankful. Became vain in their imaginations. Their minds were darkened. Blindness let to idolatry. Idolatry led to moral corruption. They are without excuse. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is the Jew under condemnation? Give Scripture. <u>Yes. Rom. 3:19 ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What knowledge does the law give us? <u>Knowledge of sin. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is the source of Justification? <u>Grace', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does grace mean? <u>Unmerited favor ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Is Christian service payment for God&rsquo;s grace? <u>No&#44; expression of love and devotion. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is grace based on the sinner&rsquo;s merit or demerit? <u>Absolutely apart from merit or demerit. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Is grace treating a person better than he deserves? ','Grace is neither treating a person better or worse than he deserves. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Is grace independent of man&rsquo;s work? ','Grace is independent of man&rsquo;s works. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the difference between law and grace? ','Law says &ldquo;pay all&rdquo;; grace says &ldquo;all is paid.&rdquo; ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does &ldquo;prevenient grace&rdquo; mean ? <u>Going before ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does &ldquo;habitual grace&rdquo; mean? ','The effects of the indwelling of the Spirit resulting in fruit. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does &ldquo;actual grace&rdquo; mean? ','Enables man to live right ', 5, NULL, 1, 1, 0, 0),


/* SQ: 6 */
(NULL, ##, 'What is the grounds of justification?','Christ&rsquo;s Righteousness.', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'How can God treat a sinner as a righteous person?','because he provides for him righteousness.', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Is it right to give the title of &quot;good&quot; and &quot;righteous&quot; to one who has not earned it? Explain.','Yes&#44; because Jesus Christ has earned it for and on behalf of the sinner.', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does redemption mean?','complete deliverance by a price paid. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What was the price paid for our righteousness?','Christ&rsquo;s atoning death.(The blood) ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Why does man need righteousness?','because man must appear before God and heaven clothed in the garment of a perfectly righteous character. (Rev. 19:8) ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Righteousness is imputed; but is it also imparted?','Righteousness is imputed in justification and imparted in regeneration.. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is a <i>propitiation</i>?','that which secures God&rsquo;s favor for the undeserving. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Why did Christ die? (To save…and secure what?) ','Christ died in order to save us from God&rsquo;s righteous wrath and to secure His favor. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What are the sinners&rsquo; garments considered to be in the eyes of God?','defiled and tattered; &ldquo;filthy rags&rdquo;; in the eyes of God. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'Why was the death of Jesus a perfect act of righteousness?','it satisfied God&rsquo;s Law. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'In speaking of the provision of righteousness&#44; what does <i>imputation</i>mean?','Reckoning Christ&rsquo;s righteousness to our account. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is <i>regeneration</i>?','being born into the divine family of God . ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does &quot;being in Christ&quot; speak of?','Answer: The change of position . ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What does &quot;Christ being in you&quot; speak of?','Answer: The change of conduct . ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is the means of justification?','The means of justification is faith. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the instrument which appropriates the righteousness of God?','Faith ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What are the three operations of faith?','Faith appropriates, Faith applies, Faith activates', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the actual operation of faith?','Faith not only passively receives&#44; but also actively uses what God bestows.', 5, NULL, 1, 1, 1, 1),



/* SQ: 7 */
(NULL, ##, 'What is Regeneration? ','Impartation of new and higher life in Christ; being born into the divine family; ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What does the N.T. describe Regeneration as? ','A birth&#44; a cleansing&#44; a quickening&#44; a creation&#44; a resurrection. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Why does man need Regeneration? ','Man is spiritually dead. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What were the three things revealed in the words of Nicodemus? ',' <u>Lack of life&#44; lack of conviction&#44; lack of knowledge </u>. ', 5, NULL, 1, 1, 1, 1), 
(NULL, ##, 'What was Nicodemus&rsquo; first question? ', ' <u>How can a man be born when he is old? ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What was his second question? ','Can he enter the second time into his mother&rsquo;s womb&#44; and be born?', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What was his third question? ','How can these things be? ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What was Jesus&rsquo; first question to Nicodemus? ','Art thou a master of Israel and knowest not these things? ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is the deepest and universal need of all? ','A change of the whole nature and character ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is the means of Regeneration? ','The divine Agent of the Holy Spirit and human reparation. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'Who is involved in Regeneration? ','The Trinity. The Father&#44; the Son&#44; and the Holy Ghost. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the human preparation in Regeneration? ','Repentance&#44; faith&#44; and confession. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is the meaning of the word &ldquo;adoption&rdquo;? ','Adoption means giving the position of sons. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What are the effects of Regeneration?','Positionally: born of God. Spiritually: united with God. Practically: righteous</u><u>living</u>. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What kind of term is &ldquo;adoption&rdquo;? ','Adoption is a legal term. ', 5, NULL, 1, 1, 1, 1),
(NULL, ##, 'What is new in Rom. 6:4?<u>Newness of life. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is new in Ezek. 36:26?<u>A new heart. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is new in Ezek. 11:19? <u>A new spirit. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'What is new in Eph. 4:24? <u>A new man. ', 5, NULL, 1, 1, 0, 0),
(NULL, ##, 'How will a person born of God demonstrate the fact of being a new man? ','Hatred of sin&#44; practice deeds&#44; brotherly love&#44; victory over the world. ', 5, NULL, 1, 1, 1, 1);