<?php
return [
['<h1>','The Christian Responsibility to Cults','Wajibu ya kikristo kwa maibada','</h1>'],
['<p>','What is every Christian&apos;s primary responsibility with regard to cults? To be true and faithful stewards with the Word of God! What makes cultic points of view attractive? They have parts of truth&mdash;some truth but it is the mixture that is dangerous. We are duty bound to be so familiar with truth that we can detect when something is only a little &lsquo;off.&rsquo; The Believer has been given power and authority over all the power of the enemy.','Kila wajibu ya kwanza ya kikristo kuhusu maibada ni nini? Kuwa vijakajzi wa kweli na waminifu wa neno la Mungu! Ni ni nini imeifanya ono ya maibaida iwe yenye kuvifa? Yamekuwa se hemu ya kweli – Ya kweli nyingine&#44; lakini ni mchanganyo ndiyo imekuwa ya hatari. Tumekuwa kwa kazi wenye kufungwa ile tuwe wenye kozoeana na kweli kwa kuweza kutambua wakati neno imekuwa tu kidogo “nje” Mwaminio alipewa uwezo na mamlaka juu ya uwezo wote wa adui.','</p>'],
['<h2>','The Power and Authority of the Believer','Uwezo na mamlaka ya mwaminio','</h2>'],
['<h3>','The Believer&apos;s Power and Authority is from God.','Uwozo na mamlaka ya mwaminio imetoka kwa Mungu','</h3>'],
['<blockquote>','Luke 9:1&mdash;Then he called his twelve disciples together&#44; and gave them power and authority over all devils&#44; and to cure diseases.','Luka 9:1- Akawaita wale thenashara&#44; akawapa uwezo na mamlaka juu ya pepo wote na kuponya maradhi.','</blockquote>'],
['<blockquote>','1 Peter 5:8&mdash;Be sober&#44; be vigilant; because your adversary the devil&#44; as a roaring lion&#44; walketh about&#44; seeking whom he may devour:','1 Petro 5:8- Muwe na kiasi&#44; na kukesha; kwa kuwa mshifaki wenu ibilisi&#44; kama samba angurumaye&#44; huzunguka zunguka&#44; akitafuta mtu ammeze!','</blockquote><ul>'],
['<li>','Be of a sober spirit','Uwe na roho ya kiasi','</li>'],
['<li>','Be vigilant','Uwe mwenye kukesha','</li></ul>'],
['<p>','The authority of the Believer is over the devil and his efforts to destroy God&apos;s purpose for our lives. One of the <strong>most important messages</strong> is to be considered in this lesson is that God has invested into the Believer His power and authority.','Mamlaka ya mwaminio ni juu ya Ibilisi na nguvu yake ya kuharibu mpango wa Mungu kwa ajili ya maisha yetu. Mmoja ya majumbe ya muhimu ya kutafakari katika fundisho hii ni ya kuwa Mungu alimkirimia mwaminio uwezo na mamlaka yake.','</p>'],
['<blockquote>','Luke 9:1&mdash;Then he called his twelve disciples together&#44; and gave them power and authority over all devils&#44; and to cure diseases.','Luka 9:1- Akawaita wale thenashara&#44; akawapa uwezo na mamlaka juu ya pepo wote na kuponya maradhi.','</blockquote>'],
['<blockquote>','John 1:12&mdash;But as many as received him&#44; to them gave he power to become the sons of God&#44; even to them that believe on his name.','Yohana 1:12- Bali wote waliompokea aliwapa uwezo wa kufanyika. Watoto wa Mungu&#44; ndio wale waliaminio jina lake;','</blockquote>'],
['<blockquote>','Matt. 10:1&mdash;And when he had called unto him his twelve disciples&#44; he gave them power against unclean spirits&#44; to cast them out&#44; and to heal all manner of sickness and all manner of disease.','Mathayo 10:1- Akawaita wanafunzi wake kumi na wawili&#44; akawapa amri juu ya pepo wachafu wawatoe&#44; na kupoza magonjwa yote na ndhaifu wa kila aina.','</blockquote>'],
['<blockquote>','2 Cor. 10:8&mdash;For though I should boast somewhat more of our authority&#44; which the Lord hath given us for edification&#44; and not for your destruction&#44; I should not be ashamed:','2 Wakorintho 10:8- Maana&#44; nijapojisifu zaidi kidogo kwa ajili ya mamlka yetu (tuliyopewa na Bwana&#44; tupate kuwajenga wala si kuwangusha)&#44; sitat hayarika:','</blockquote>'],
['<blockquote>','Titus 2:15&mdash;These things speak&#44; and exhort&#44; and rebuke with all authority. Let no man despise thee.','Tito 2:15- Nena&#44; maneno&#44; onya na kukaripia kwa mamlaka yote&#44; asikudharau mtu awaye yote.','</blockquote>'],
['<p>','The Believer cannot be hindered or stopped by the devil if he knows how to properly use what God has promised and provided. We must be aware of God&apos;s provision&#44; but we must also learn how to put that promise to practice.All that God has promised is added to our lives as we diligently believe Him. Such faith requires implicit obedience. Believe and Obey.','Mwaminio hawezi kuzuiwa au kusimamishwa na ibilisi ikiwa amejua jinsi ya kutumia vizuri ile mungu alihaidi na kutolea. Imetupasa kuwa ufahamu ya matoleo ya Mungu&#44; lakini imetupasa tena kujifunza jinsi ya kutia yale ahadi katika matendo. Yo yote ambayo mungu alihaidi imeongezwa kwa maisha yetu kadiri tumejitahidi kimwaminia. Hiyo imani imehitaji kweli utii. Aminia na utii','</p>'],
['<h3>','What does this Power and Authority Mean?','Uwezo na mamlaka hii maana yake nini?','</h3>'],
['<p>','<strong>Five different Greek words…</strong>','Matambko tano tofauti ya kiyunani…','</p>'],
['<p>','<strong>exousia</strong>&#44; Gr. authority; privilege&#44; capacity&#44; competency&#44; mastery ','Exousia&#44; Kiyunani&#44; mamlaka&#44; ziada&#44; uwezo&#44; ushotelevu&#44; uwalimu.','</p>'],
['<p>','<strong>dunamis</strong>&#44; Gr. force&#44; specially&#44; miraculous power ','Dunamis&#44; kiyunani. Nguvu&#44; na zaidi uwezo wa kutenda myufeza','</p>'],
['<p>','<strong>kratos</strong>&#44; Gr. vigor ("great") --dominion&#44; might(-ily)&#44; power&#44; strength.','Kratos&#44; kiyunani Nguvu (“Mku”) Utawala nguvu&#44; uwezo.','</p>'],
['<p>','<strong>arche</strong>&#44; Gr. a commencement&#44; or chief&#44;first (estate)&#44; magistrate&#44; power','Arche&#44; kiyunani&#44; mwanzo&#44; au ya kwanza (kitu)&#44; kadhi&#44; uwezo.','</p>'],
['<p>','<strong>…that are translated almost interchangeably.</strong>','&hellip;ambao imetafsiriwa sawa sawa.','</p><table><tbody><tr>'],
['<th>','Greek','Kiyunani','</th>'],
['<th>','Colossians 2:15','Wakolosai 2:15','</th>'],
['<th>','Luke 9:1','Luka 9:1','</th>'],
['<th>','Luke 10:19','Luka 10:19','</th>'],
['<th>','Ephesians 1:19','Waefeso 1:19','</th>'],
['<th>','Ephesians 1:21','Waefeso 1:21','</th></tr><tr>'],
['<td>','exousia','Exousia','</td>'],
['<td>','powers','“Uwezo”','</td>'],
['<td>','authority','“Mamlaka”','</td>'],
['<td>','power','“Uwezo”','</td>'],
['<td>','-','-','</td>'],
['<td>','power','“Uwezo”','</td></tr><tr>'],
['<td>','dunamis','Dunamis','</td>'],
['<td>','-','-','</td>'],
['<td>','power','“Uwezo”','</td>'],
['<td>','power','“Uwezo”','</td>'],
['<td>','power','“Uwezo”','</td>'],
['<td>','might','“Nguvu”','</td></tr><tr>'],
['<td>','kratos','Kratos ','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','power','“Uwezo”','</td>'],
['<td>','-','-','</td></tr><tr>'],
['<td>','arche','Arche ','</td>'],
['<td>','principalities','“Ukuu”','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','principality','“Ukuu”','</td></tr><tr>'],
['<td>','kuriotes','Kuriotes ','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','-','-','</td>'],
['<td>','dominion','“Utawala”','</td></tr></tbody></table>'],
['<p>','Power and authority are so intimately related&#44; it is difficult to separate the one from the other. Both power and authority are promised and at no time do we have to be with power and without authority or vice versa.For the sake of study&#44; &lsquo;power&rsquo; and &lsquo;authority&rsquo; are distinct in that:- Power is CAPACITY. &lsquo;18-Wheeler&rsquo; -the capacity to go 80 mph- Authority is RIGHT. &lsquo;Police Officer&rsquo; -the right to say&#44; &lsquo;Stop!&rsquo;','Uwezo na mamlaka ni yenye kuambakana zaidi&#44; ni kigumu kutenga moja kwa ingine. Uwezo na mamlaka yote imehaidiwa na hata kwa wakati moja hatuwzei kuwa na uwezo bila mamlaka na vivyo hivyo. Kwa mafia ya mafunzo “uwezo” na “mamlaka” imetofauti katika hii gari. “ya mipeto” kumi na mnane. Uwezo ni NGUVU. Nguvu ya kwenda safari ya kilomita themanini kwa saa moja. Mamlaka ni HAKI. “Akidapalisi” – Haki ya kusema” Hima”','</p>'],
['<h3>','Qualifications to Exercise the Authority of God','Kustahili kutumikisha mamlaka ya Mungu','</h3>'],
['<p>','What are the Qualifications to exercise this Authority?','Ni nini imestahili kwa kutumikisha hii mamlaka?','</p>'],
['<h4>','We need to have right knowledge with a true experience.','Tumehitaji kuwa na ufahamu sawa na mazoezi.','</h4>'],
['<p>','Eph. 1:3&#44; 19&#44; 21 a place or position of power and authority promised.2 Peter 1:2-10 Are we using the power and authority that is promised?','Waefeso 1:3&#44;19&#44;21- mahali au msimamo wa uwezo na mamlaka yenye kuhaidiwa. 2 Petro 1:2-10- Tumeyatumwa uwezo na mamlaka ambayo ilihaidiwa?','</p>'],
['<blockquote>','Hebrews 12:2&mdash;Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross&#44; despising the shame&#44; and is set down at the right hand of the throne of God. (Acts 19:14-16)','Waebrania 12:2- tukimtazama yesu&#44; mwenye kuanzisha na mwenye kutimiza imani yetu; ambae kwa ajili ya furaha iliyowekwa mbele yake aliustahimili msalaba na kuidharau aibu&#44; naye ameketi mkono wa kuume wa kiti cha enzi cha mungu. (Matendo 19:14-16)','</blockquote>'],
['<h4>','We need to exercise faith with power.','Tumehitaji kutumikisha imani na uwezo','</h4><ul>'],
['<li>','To live in accordance with Truth I Tim. 2:7; Titus 1:1','Kuishi kuambatana na kweli 1 Timotheo 2:7; Tito 1:1.','</li>'],
['<li>','Faith with power II Thes.1:11; Acts 6:8; I Cor. 2:5; I Pt. 1:5','Imani na uwezo II Wathesalonike 1:11; Matendo 6:8; I Wakorintho 2:5; I Petro 1:5.','</li></ul>'],
['<blockquote>','Matthew 23:23&mdash;Woe unto you&#44; scribes and Pharisees&#44; hypocrites! for ye pay tithe of mint and anise and cummin&#44; and have omitted the weightier matters of the law&#44; judgment&#44; mercy&#44; and faith: these ought ye to have done&#44; and not to leave the other undone.','Mathayo 23:23- ole wenu waandishi na mafarisayo&#44; wanafiki! Kwa kuwa mnalipa zaka za mnanaa na bizari na jira&#44; lakini mmeacha mambo makuu ya sheria&#44; yaani adili&#44; na rehema&#44; na imani&#44; hayo imewapasa kuyafanya&#44; wala yale mengine msiyaache.','</blockquote>'],
['<h4>','We must demonstrate true humility&mdash;complete confidence in God&apos;s power.','Imetupasa kuonyesha unyenyekevu ya kweli – aminio yote katika uwezo wa mungu.','</h4>'],
['<p>','Luke 10:20; 2 Cor. 7:9; Rom. 10:5; Gal. 2:20; James 4:6&#44; 10; 1 Peter 5:5&#44; 6; Micah 6:8; John 6:57','Luka 10:20; 2 Wakorintho 7:9; Warumi 10:5; Wagalatia 2:20; Yakobo 4:6&#44;10; 1 Petro 5:5&#44;5; Mika 6:8&#44; yohana 6:57 ','</p>'],
['<h2>','The Need to Confront','Haja ya kurekipisha','</h2>'],
['<p>','Do we care enough to confront? Before comfort there must be a true confronting. Read Galatians 6:1-10.','Wumetunza ya kutosha kabla ya kushambulia? Kabla ya faraja kumepashwa kuwapo kweli. Usome kwenye wagalatia 6:1-10.','</p>'],
['<blockquote>','Gal. 6:1&#44;2&mdash;Brethren&#44; if a man be overtaken in a fault&#44; ye which are spiritual&#44; restore such an one in the spirit of meekness; considering thyself&#44; lest thou also be tempted. 2 Bear ye one another&apos;s burdens&#44; and so fulfill the law of Christ.','Wagalatia 6:12- Ndungu zangu&#44; mtu akighafilika katika kosa lolote&#44; ninyi mlio a koho mrejezeni upya mtu kama huyo kuvi roho ya upole&#44; ukijinagalia&#44; nafsi yako usiji ukajaribiwa wewe mwenyewe. 2 Mchukukiane mizigo na kutimiza hiyo sheria ya kristo.','</blockquote>'],
['<p>','What is the Churches responsibility when a professing Christian commits a sin? Confronting is for true brethren that are spiritual to do. True brethren that are spiritual have the responsibility to confront the man that has been overtaken in a fault that he might be restored.','Ni nini wajibu ya makanisa wakati mkristo mwenye kutenda ametenda dhambi? Kwekikisha ni kwa ndugu wa kweli. Ya rohoni kufanya. Ndugu wa kweli ambae ni wa rohoni wana wajibu ya kumsikiliza kwa swali mtu ambae alighafilika katika kosa ili awezi kurekibishwa.','</p>'],
['<h3>','Brethren&#44; if a man be overtaken in a fault…','Ndugu&#44; kama mtu ameghafilika katika kosa&hellip;','</h3>'],
['<p>','Always confront the wrong with the truth. Spiritual brethren must use the truth of Gods&rsquo; Word to confront the wrong. (John 1:11; Ps 69:8; 122:8; 133:1; Prov. 6:10-19) Confronting wrong is always done while depending on the grace of God to help. (Gal. 1:6; 2:21; 6:18) Where the grace of God is depended on there will be boldness and a prayer life. Boldness and a consistent prayer life is so important in striving for the restoration of the one overtaken. Because he is hurt&#44; hopeless and many times bitter&#44; it is impossible to renew him to repentance.','Sikuzote kutamsaha mabay na kweli. Ndugu rohoni amepashwa kahumia kweli ya neno la mungu makusudi kudamsho mabaya (yohana 1:11; Zaburi 69:8; 122:8; 133:1; Mithili 6:10-19) Kukamisha mabaya ni imefunyika sikuzote wakati mtu ametegamia neema ya mungu imusahidie. (wagalatia 1:6; 2:21;6:18). Kwenye neema ya Mungu imetegemewa kumakuwapo bidii na na maisha ya sala. Bidii na maisha kanulifu ya sala ni ya muhimu zaidi kwa kujitahhidi kurejeza alio ghofilika kwa sababu ameguswa amekosa tumaini na nyakati nyingi amekuwa na uchungu&#44; ni kigumu kumrejeza kwa utubio.','</p>'],
['<p>','Paul confronted Peter:','Paulo alimrekibisha Petro:','</p>'],
['<blockquote>','Galatians 2:11&mdash;But when Peter was come to Antioch&#44; I withstood him to the face&#44; because he was to be blamed.In 3 John 1:9&#44;10&#44; Paul commits to confronting Diotrephes during his next visit.','Wagalatia 2:11- Lakini Kefa (Petro) alipokuja antiokia&#44; nail shindana naye uso kwa uso&#44; kwa sababu alistahili hukumu. Katika 3 yohana 1:9&#44;10&#44; Paulo amejitolea kumrekibisha Dio triphes wakati ya safanri yake ijayo.','</blockquote>'],
['<p>','I Cor. 8:12&mdash;But when ye sin so against the brethren&#44; and wound their weak conscience&#44; ye sin against Christ.','I Wakorintho 8:12- thoyo&#44; mkiwatenda dhambi ndugu yenu na kuitia jiraha dhamiri iliyo dhorifu&#44; mnamtenda dhambi christo.','</p>'],
['<p>','Rom. 8:12&mdash;Therefore&#44; brethren&#44; we are debtors&#44; not to the flesh&#44; to live after the flesh.','Warumi 8:12- Bisi&#44; kama ni hiiyo ndugu&#44; tu wadeni&#44; si wa mwili tuishi kwa kufuata mambo ya mwili.','</blockquote>'],
['<p>','Rom. 7:4; 8:13; 9:3; 10:1; 11:25; 15:15&#44; 30; 16:17; 1 Cor. 1:10&#44; 11; 3:1; 4:6; 6:5&#44; 8; 7:24','Warumi 7:4; 8:13; 10:1; 11:25; 15:15&#44; 30&#44;; 16:17; 1 Wakorintho 1:10&#44; 11; 3:1; 4;6; 6:5;8;7:24','</p>'],
['<blockquote>','1John 3:16&mdash;Hereby perceive we the love of God&#44; because he laid down his life for us: and we ought to lay down our lives for the brethren.','Ifohana 3:6- Katika hili tumelifahamu pendo&#44; kwa kuwa yeye aliutoa uhai wake kwa ajili yetu; imetupasa na sisi tuutoa uhai wetu kwa ajili ya hao ndugu.','</blockquote>'],
['<p>','<strong>Instead of watching our wounded soldiers fall to the way side and simply continuing on our solo march&#44; we should carry a deep concern for our brethren that have fallen. We are commanded in this to the very extant of laying down our lives for the brethren&mdash;our life for theirs.</strong>','Badala ya kutazama majeshi letu ambae walijarahaliwa kuanguka upande wa njia na kwendelea kwa raisi matembezi yetu imetupasa kuwa na shumriko kuu kwa ajili ya ndugu ambaye walianguka. Tumeamuriwa kwa hiyo kuitaa uhai wetu kwa ajili ya nduguuhaiwetu kwa ajili yao.','</p>'],
['<p>',' The word &lsquo;fault&rsquo; (trespass&#44; or sin) means to stumble or fall. No matter how many have fallen we need to carry to them a message of reconciliation to God &lsquo;Be reconciled to God.&rsquo; Rom. 4:25; 5:15-20; II Cor. 5:17-20 ; Eph.2:1-5&mdash;But God…','Tamko “Fault” (Kosa&#44; au dhambi) maana kukwaa au kuanguku. Si ne neno mar ngapi walianguka&#44; tumehtaji kuwapelekea ujumbe wa kupatana na Mungu « Upatane na Mungu » warumi 4 ;25 ; 5 :15-20 ; II wakorintho 5:17-20 ; waefeso 2 :1-5- Lakini mungu….','</p>'],
['<blockquote>','James 5:16&mdash;Confess your faults one to another&#44; and pray one for another&#44; that ye may be healed. The effectual fervent prayer of a righteous man availeth much.','Yakobo 5 :16- Ungamini dhombi znu ninyi kuwa ninyi&#44; na kuombeana&#44; mpate kuponywa. Kuomba kwake mwenye haki kwafaa sana&#44; akumba kwa bidii.','</blockquote>'],
['<h3>','Ye that are <strong>spiritual</strong>…','Ninyi wa rohoni…','</h3>'],
['<blockquote>','I Cor. 2:15&mdash;But he that is spiritual judgeth all things&#44; yet he himself is judged of no man.','I Wakorintho 2 :15- Lakini mtu wa rohoni huyatambua yote&#44; wala yeye hatambuliwi na mtu.','</blockquote>'],
['<blockquote>','I Thess. 5:21&mdash;Prove all things; hold fast that which is good.','I Wathesalonike 5 :21- Jaribuni mambo yote ; lishikeni lililo jema.','</blockquote>'],
['<h4>','Restore such an one Mt 4:21 Mt 21:16 1Co 1:10','Mujeshe yule mtu mathayo 4:21 1 wakorintho 1:11.','</h4>'],
['<h4>','In the spirit of meekness','Katika roho ya upole','</h4>'],
['<h4>','Considering thyself&#44; lest thou also be tempted','Ukijiangalia nafsi yalo usiji ukajaribiwa wewe mwenyewe.','</h4>'],
['<h3>','Bear ye one another&apos;s burdens…','Muchukukiane mzigo&hellip;','</h3>'],
['<p>','The best possible way to restore someone is to confront them face to face about their behavior&#44; beliefs and attitudes. It is not easy and most people try to avoid confrontation (Matt. 18:15)&#44; but it becomes so helpful and necessary. More often than not we are dealing with issues in peoples&rsquo; lives that concern eternity. Our own discomfort and unease are a small price to pay if we can win a brother!','Jinsi bora ya kumrejesha mtuni kushindana uso kusi uso kuhusu mwenendo yao&#44; aminio&#44; na tabia. Si raisin a watu wengi wameepuka mashindano (mathayo 18:15)&#44; lakini imekuwa ya kusaidia na ya lazima zaidi. Kila mara zaidi tumeusika na mashida katika maisha ya watu kuhusu milile. Masumbufu yetu ni thamani ndogo ya kulipa kama tumeweza kupata ndugu!','</p>'],
['<h4>','Situations when confrontation is necessary:','Nyakati mashindano ni ya muhimu:','</h4>'],
['<h5>','When someone has offended or purposely hurt you.','Wakati mtu amekukosea au amekuhuzunikisha makusudi','</h5>'],
['<h5>','When someone is displeasing to God through their behavior','Wakati mtu hamfurahishi hungukwa mwenendo','</h5>'],
['<h5>','Only under submission to the Pastor and in the fear of God.','Kwa utii tu kwa muchungaji na katika kunda mungu.','</h5>'],
['<h4>','Questions to ask yourself before confrontations.','Swali ya kujiuliza mwenyewe mbele ya mashindano','</h4>'],
['<h5>','What is my motive?','Sababu gain imenisukuma?','</h5>'],
['<p>','Do I genuinely care about this person or are they just getting on my nerves? Correct motivation for confrontation includes: 1)To restore the person to fellowship and growth. 2)For God to show His love for them through you. 3)To help the person to know the truth and to love it and to live it','Nimenjali kweli kweli huyo mtu au wamenikasirisha tu? Sababu kamili ya mashindano ni: 1) Kumajisha mtu kwa umoja na maendeleo 2) Ili mungu aonyeshe pendo lake kwa ajili yao kwa njia yako. 3) Kwa kumasaidia mtu ajui kweli na kuipenda na kuiishi.','</p>'],
['<h5>','Am I sure God is leading me to confront right now?','Nina hakikisho ya kuwa Mungu amenyongoza ili kushindana sasa hivi?','</h5>'],
['<p>','Pray for the Holy Ghost to deal with them and lead you. Take your time and pray much about the confrontation. Am I sure God is leading? Have I fully examined mine own self in this area I desire to confront?Mat. 7:3&#44; 4; II Cor. 13:5','Omba ili Roho mtakatifu awe nao na awaongoze. Wumilia na omba zaidi kuhusu mashindano. Nina hakikisho ya kuwa Mungu ameongoza ? nilitazama nafsi yangu yote katika eneo ambayo nimetaka kushindana? Mathayo 7 :3&#44;4 ; II Wakorintho 13 :5','</p>'],
['<h5>','Have I really tried to understand the person&apos;s action?','Nilijaribu kweli kuelewa tendo la mtu?','</h5>'],
['<p>','Do I have the facts right? Go to the Brethren that can judge brethren righteously. (Deut. 1:16)','Nina mambo yote sawa ? uwaendee ndugu ambae wameweza kuwatambua ndugu katika haki.','</p>'],
['<h5>','Have I planned what I would say?','Ulipanga mameni ambaye utaisema ?','</h5>'],
['<p>','Your tone of voice&#44; the words and the way you use the words are very important. Especially do not use anger as your dominant expression. (Prov. 12:18; James 1:19; Psalms 115:3; Prov. 17:9; Deut. 13:14)','Nguvu ya sauti yako&#44; matamko na jinsi umetumia matamko yake ni ya muhimu sana. Hasa usitumie hasira kama maneno yako makuu. (Mithili 12 :18 ; Yakobo 1 :19 ; zaburi 115 :3 ; Mithili 17 :9 ; Kumbu-kumbu la Torati 13 :14)','</p>'],
['<h5>','Have I anticipated what they might say and how I would answer?','Nilitangulia maneno ambayo waliweza kuyanena na jinsi gani nitajibu ?','</h5>'],
['<h5>','Have I considered the consequences?','Nilitazama matokeo ?','</h5>'],
['<p>','Dangerous people and things need to be confronted and stopped both in the church and in society at large. (Acts 20:26; Gal. 2:11; Mat. 16:23)','Watu na mambo yenye hatari imehitaji kushambuliwa na kuzuiwa kanisani na maishani kwa ujumla (Matendo 20 :26 ; Wagalatia 2 :11 ; Mathayo 16 :23)','</p>'],
['<blockquote>','I Sam. 17:29&mdash;And David said&#44; What have I now done? Is there not a cause?','1 Samueli 17 :29&mdash; Na Davidi&#44; Nimefanya nini sasa ? Hakuwapo sababu ?','</blockquote>']
];