<?php
return [
['<h1>','Curious Fascination of the Darkness','Mtu na hiyo hali ya mafikiri maeanika tu kila siku na kwenda kwa makazi yake bila hata mafikiri ya kuhusu matokeo au vipi mwenendo wake iliweza kugusa wengine. Hakuna mpango&#44; kitungo&#44; wala sabaa kwa maisha ya mtu hisipokuwa tu kutumikia siku ingine upendelevu wa giza wenye kushangaza ','</h1>'],
['<h2>','Occult','Maarifa ','</h2>'],
['<blockquote>','I John 4:1—Beloved&#44; believe not every spirit&#44; but try the spirits whether they are of God: because many false prophets are gone out into the world.','I Yohana 4:1- Wapenzi&#44; msiiamini kila roho&#44; bali zijari uni hizo roho&#44; kwamba zimetokana na Mungu&#44; kwa sababu manabii wa wango wengi wametokea duniani.','</blockquote>'],
['<h3>','Definition of the Occult','Mafasirio ya maarifa','</h3>'],
['<p>','The word Occult comes from the Latin word ocultus: things hidden&#44; secret&#44; and mysterious. The occult deals with operations or events which seem to depend upon human powers to go far beyond the five senses. The occult deals with the supernatural&#44; the presence of demonic forces&#44; and even the paranormal.','Iamko maarifia imetoka kwenye tamko ya kilatin Ocultus: mambo yenye kusikirika&#44; siri&#44; nay a ajabu. Uchawi imeamb atana na matendo au mambo ambayo imeonekana kutengemea uwezo wa mtu nje ya vipaji tano vya njia ya kusikia miwilini. Uchawi umeambatana kwa kazi na nguvu ya nje ya asili&#44; kuwapo kwa nguvu ya mashetani&#44; na hata yalio kufanana ya kawaida. ','</p>'],
['<h3>','Danger of the Occult','Habari ya maarifa','</h3>'],
['<p>','It is dangerous to deny its existence or to be ignorant of its devices. An equal error is to have an unhealthy interest in the occult. (II Cor. 2:11; Rom. 16:9; I Tim. 4:1)A Major Warning. Playing around with the occult will lead to serious mental and spiritual problems. Be Aware of the ongoing spiritual battle between the Kingdom of God and the kingdom of satan. We need to be aware of the workings of the satanic realm but not to the point of unhealthy fascination&#44; obsession or any kind of involvement. God judges and condemns all traffic with demons. (Ex. 20:3; Mat.4:10; John 12:31; I Cor. 10:20; Eph.4:27; 1 John 3:8)','Ni ya hakari kukanan maisha yake au kutokujua hila yake. Kosa ya kawaida ni kutokuona faida katika uchawi (II Wakorintho 2:11; Warumi 16:9; I Timotheo 4:1) Onyo kuu. Kucheza na maarifa imepeleka kwenye mashida kuu ya rohoni na akilinii uwe katika ufahamu ya mapambano yenye kuendelea ya rohoni katika ufalme wa mungu na washetani. Tumehitaji kuyafahamu na kazi ya ulimwengu wa shetani lakini siyo kwa hali ya kuwa upendelevu isiyo kuwa bora&#44; upofu&#44; au aina yo yote ya kujitumbukiza. Mungu amehukumu na kulaumu maambatano yote na mashetani (kutoka 20:3; Mathayo 4:10; Yohana 12:31; I wakorintho 10:20; Waefeso 4:27;1 Yohana 3:8)','</p>'],
['<blockquote>','1 Tim. 4:1—Now the Spirit speaketh expressly&#44; that in the latter times some shall depart from the faith&#44; giving heed to seducing spirits&#44; and doctrines of devils;','I Timotheo 4:1- Basi anena waziwazi ya kwamba nyakati za mwinsho wengine wabajilenga na imani&#44; wakisikiliza roho zidanganyazo ye mashetani.','</blockquote>'],
['<h3>','Disciples of the Occult','Wanafunzi wa maarifa','</h3>'],
['<p>','What kind of people get involved in the occult?','Ni aina gain ya watu ambaye wamejitumbukiza katika maarifa?','</p>'],
['<p>','Curious&#44; easily influenced&#44; dissatisfied&#44; sad&#44; rebellious&#44; etc.(Children are greatly influenced and programmed by the filthy habits of adults.)','Wenye kutafuta kujua&#44; ambae wameweza kushawishwi kwa raisi&#44; wenye uzuri&#44; wasio faidika&#44; wenye kutomboka&#44; na kadhalika. (Watoto wamashawishwi zaidi na kupotoshwa na tabia mbavu ya wakuu)','</p>'],
['<p>',' Remember:- There is the Occult—is an organized group.- There are Occult practices—are collected from the influence of the occult.','Ukumbuke: Kunakuwapo uchawi-ni kundi yenye ongozi sawa','</p>'],
['<p>','Most are totally unaware of it&#44; but the occult influence is spread through TV&#44; books&#44; Radio&#44; schools&#44; societies and internet.','Kunakuwapo matendo ya maarifa- ya mechutuliwa toka ushawishi wa maarifa wengi honueto katika ufamu yo yote ya hiyo&#44; bali ushawishi wa maarifa umetangazwa kwa njia ya tivi&#44; vitabu&#44; redo&#44; mashuole&#44; makundi ya watu na inteneti. ','</p>'],
['<h4>','Escapists—one who will not accept responsibility and reality.','Watoro-mtu ambaye hatakuyakubali wajibu na kweli.','</h4>'],
['<p>','An old cliché: The devil made me do it','Picha ya zamani – Ibilisi alinisfanya mimi kuyatenda.','</p>'],
['<h4>','Superstitious—explaining the natural by invisible forces and rules at work. &lsquo;Old wives fables&rsquo; and silly lore of men.','Wenye kuaminia maarifa- wenye kufasiria ya asilikwa njia ya nguvu ambayo haionikani kna makanuni yeny »e kuwa kwa kazi. Hadithi ya wake wazee » na wanaume wapumbavu…','</h4>'],
['<h4>','Victims- Victims&#44; yes but were they watching&#44; praying and really seeking the Lord?','Wenye kungua: Wenye kunguwa&#44; ndiyo lakini wametazama&#44; wameomba na kwe wametafuta Bwana?','</h4>'],
['<p>','Victims <strong>but</strong>: Uncommitted&#44; Curious&#44; Gullible&#44; Naive&#44; Inconsistent&#44; Rebellious&#44; Crazy&#44; Conditioned&#44; Credulous.','Wenye kungua lakini: Si wenye kujitolea; Wa dhaifu; Wenye kutafuta kujua; Wasiyo ambatana; Wenye kutomboka; Wenye kuvunikika; Wenye kulazimishwa; Wenye kusadiki','</p>'],
['<p>','Knowing God judges all dealings with the devil there should never be any room to negotiate or compromise with the devil. As a Christian we are to be spiritually discerning all things.','Hali kujua ya kuwa mungu amehukumu viote ambao wameambatana na Ibilisi hakupashwi kuwapo nafsi ya kuusiyana au kupatana na Ibilisi. Kama Mcristo imetupasa kuwa kukadiria rohoni mambo yote&#44;','</p>'],
['<p>','1 Corinthians 2:15; 1Co 6:2&#44;3; 1 Cor. 11:31; Heb 5:14.',' I Wakorintho 2:15; 1 Wakolosai 6:2&#44;3; I Wakorintho 11:31; waebrania 5:14.','</p>'],
['<h2>','Witchcraft','Uchawi (Uchawi ni mabaya maconi mwa Mungu)','</h2>'],
['<blockquote>','Gal. 5:21—… they which do such things shall not inherit the kingdom of God.','Walagatia 5 :21… Watu watendao mambo ya jinsi hiyo hawaurithi ufalme wa Mungu.','</blockquote>'],
['<p>','I Sam. 15:23; II Chron.33:6; Gal. 5:20; I Tim. 4:1-2; Acts 13:6-12; Acts 19:19; Mark 13:22; Deut. 18:9-14','I Samueli 19 :23 ; II Mambo ya shiku 33 :6 ; Wagalatia 5 :20 ; I Timotheo 4 :1-2 ; Matendo 13 :6-12 ; Matendo 19 :19 ; Marko 13 :22 ; Kumbu Kumbu la torati 18 :9-14.','</p><table><tr>'],
['<td>','ankhs','ankhs','</td>'],
['<td>','pyramids','piramidi','</td>'],
['<td>','lucky charms','bahati hirizi','</td>'],
['<td>','talisman','hirizi','</td>'],
['<td>','amulet','hirizi','</td></tr><tr>'],
['<td>','Zodiac','zodiac','</td>'],
['<td>','medallions','medallions','</td>'],
['<td>','games','michezo','</td>'],
['<td>','rabbit foot','sungura mguu','</td>'],
['<td>','genie in a bottle','Genie katika chupa','</td></tr><tr>'],
['<td>','Cosmetics','vipodozi','</td>'],
['<td>','bracelets','vikuku','</td>'],
['<td>','rings','pete','</td>'],
['<td>','Deck of cards','Staha ya kadi','</td>'],
['<td>','trinkets','trinkets','</td></tr> <tr>'],
['<td>','jewelry','kujitia','</td>'],
['<td>','lip stick','mdomo fimbo','</td>'],
['<td>','necklaces','shanga','</td>'],
['<td>','earrings','pete','</td>'],
['<td>','drugs','madawa ya kulevya','</td></tr><tr>'],
['<td>','mascot','mascot','</td>'],
['<td>','astrology symbols','alama Astrology','</td></tr></table>'],
['<h3>','Beware that the devil exists','Fanya angalisyo ya kuwa Ibilis yuko ','</h3>'],
['<p>','2 Cor. 11:14-15','2 Wakorintho 11:14-15','</p>'],
['<h3>','Beware of his motive','Jihadharini nia yake','</h3>'],
['<p>','He wants adoration worship attention Mt 4:1-11','Fanya angalisho kwa sababu yake ametaka ibada ya kusujudu Mathayo 4:1-11','</p>'],
['<h3>','Beware of his methods','Fanya angalisho kwa mbimu yake ','</h3><ul>'],
['<li>','To devour I Peter 5:8; John 10:10','Kupepeka    I petro 5:8&#44; Yohana 10:10','</li>'],
['<li>','To deceive 2Co 11:3; 2Th 2:9-10','Kudanganya 2 Wakorintho 11:3; 2 Wathesalonike 2:9-10  ','</li></ul>'],
['<blockquote>','Galatians 5:20—Idolatry&#44; witchcraft [pharmakeia]&#44; hatred&#44; variance&#44; emulations&#44; wrath&#44; strife&#44; seditions&#44; heresies&#44;','Wagalatia 5:20- Ibada ya sanamu&#44; uchawi&#44; uadui&#44; ngonvi&#44; wivu&#44; hasira fitina&#44; faraka','</blockquote>'],
['<blockquote>','Revelation 9:21—Neither repented they…of their sorceries [pharmakeia]…','Ufunuo 9:21- Wala hawa kuutubia…. ‘phonmakeia) Uchawi waoufunuo 18:23-… Kwa kuwa mataifa yote walidanganya kwa uchawu wako (pharmateis)','</blockquote>'],
['<blockquote>','Revelation 18:23—… for by thy sorceries [pharmakeia] were all nations deceived.','Pharmakeia&#44; chumba cha madawa  na kadhalika mbele maana yake makumizi ya dawa&#44; maarifa&#44; kiisha&#44; kufanya sumu&#44; kruisha uchawui… Katika uchawi&#44; makumizi ya yenye kuwa legevu au ya nguvu ili kuwa kwa ujumla imeshindikizwa na kuagua na mfani kwa uwezo wa maarifa&#44; na matoleo ya vyombo tofauti ya uchawi amulets&#44; na kadholika…','</blockquote>'],
['<p>',' <strong>Pharmakeia</strong> (Eng.&#44; pharmacy etc.) primarily signified the use of medicine&#44; drugs&#44; spells; then&#44; poisoning; then sorcery. . . . In sorcery&#44; the use of drugs&#44; whether simple or potent&#44; was generally accompanied by incantations and appeals to occult powers&#44; with the provision of various charms&#44; amulets&#44; etc.','Ulozi na uchawi ni vyenye kuambatana katika dhambi makuu na imehukumiwa na mungu.','</p>'],
['<p>','Sorcery and witchcraft are tied into the grossest sins and are judged of God.','Hatari yakuvumilia ubaya','</p>']
];